server:
  port: 8081
  servlet:
    context-path: /storefront

spring:
  application:
    name: storefront
  datasource:
    url: jdbc:h2:mem:storefront;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    queue:
      product-change-availability: product.change.availability.queue

warehouse:
  base-path: http://warehouseapp:8080/warehouse